// Generated by CoffeeScript 1.3.3
(function() {
  var age, gender, item, name, person, type, typeTwo, yell, _i, _len;

  name = "Scott";

  person = true;

  age = 25;

  yell = function() {
    alert(name);
    return alert(age);
  };

  if (age > 24) {
    yell();
  }

  if (name != null) {
    yell();
  }

  gender = "";

  if (gender == null) {
    gender = "Male";
  }

  type = ["Rice", "Crab", "Cucumber"];

  for (_i = 0, _len = type.length; _i < _len; _i++) {
    item = type[_i];
    if (item === "Rice") {
      "" + item + "s";
    }
  }

  type = (function() {
    var _j, _len1, _results;
    _results = [];
    for (_j = 0, _len1 = type.length; _j < _len1; _j++) {
      item = type[_j];
      if (item !== "Rice") {
        _results.push("" + item + "s");
      }
    }
    return _results;
  })();

  typeTwo = (function() {
    var _j, _len1, _results;
    _results = [];
    for (_j = 0, _len1 = type.length; _j < _len1; _j++) {
      item = type[_j];
      if (item !== "Rice") {
        _results.push(item);
      }
    }
    return _results;
  })();

}).call(this);
