// Generated by CoffeeScript 1.3.3
(function() {
  var age, gender, name, person, sushi, type, yell;

  name = "Scott";

  person = true;

  age = 25;

  yell = function() {
    alert(name);
    return alert(age);
  };

  if (age > 24) {
    yell();
  }

  if (name != null) {
    yell();
  }

  gender = "";

  if (gender == null) {
    gender = "Male";
  }

  type = ["Rice", "Crab", "Cucumber"];

  sushi = {
    kind: "Roll",
    roll: function() {
      return "Rolled";
    },
    fish: "Salmon",
    ing: {
      rice: "White",
      veg: "Cucumber"
    },
    "class": "Roll"
  };

}).call(this);
