// Generated by CoffeeScript 1.3.3
(function() {
  var age, name, person, yell;

  name = "Scott";

  person = true;

  age = 25;

  yell = function() {
    alert(name);
    return alert(age);
  };

  if (age > 24) {
    yell();
  }

}).call(this);
