// Generated by CoffeeScript 1.3.3
(function() {
  var name, person, yell;

  name = "Scott";

  person = true;

  yell = function(a) {
    var age;
    age = a;
    alert(name);
    return alert(age);
  };

  yell(25);

}).call(this);
